### ISSUE TITLE
[BUG] Exiled cat rejoins still marked as exiled

### ISSUE THREAD

**Issue by Sparrow-Moon** [scribblecrumb/clangen#32]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
ex.: A cat that was exiled and joined back through the leaders den is still counted as exiled

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Click on a cats profile
2. Click on Exile
3. Go to the Leaders den
4. Invite the exiled cat back in
5. look at manage roles

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/110138073/df514c2c-67a7-4b80-be3f-37b403b76e23)
![image](https://github.com/scribblecrumb/clangen/assets/110138073/9f9e8404-b761-42fe-848e-83ea66d71cd5)

**Comment by scribblecrumb** [comment]
Fixed
