### ISSUE TITLE
[BUG] crash error

### ISSUE THREAD

**Issue by peppst-r** [scribblecrumb/clangen#34]
**Type**: Code

**Describe the bug**
Crash upon moonskip, 

**Grade**: gamebreaking

**Reproduce**
all i know that i did before this that could have caused it is exiling a cat, inviting them back in, and then exiling them again. I tested this with other cats and couldn't reproduce the crash

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/167268625/2945b7b8-3c82-4d27-90fa-baf30d3692c5)

**Comment by scribblecrumb** [comment]
Possibly fixed, report again if encountered again
