### ISSUE TITLE
[BUG] thoughts trying to generate for exiled + driven off cats

### ISSUE THREAD

**Issue by peppst-r** [scribblecrumb/clangen#35]
**Type**: code

**Describe the bug**
I believe the game is trying to generate thoughts for a cat I exiled and then drove off

**Grade**: regular

**Reproduce**
exile cat and drive off in the same moon

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/167268625/4979ffb7-b328-4a10-88ef-0b81b4ec1b92)

**Comment by scribblecrumb** [comment]
Fixed
