### ISSUE TITLE
[BUG] crash upon hunting down an exiled cat

### ISSUE THREAD

**Issue by peppst-r** [scribblecrumb/clangen#36]
**Type**: code

**Grade**: gamebreaking

**Reproduce**
exile cat and then hunt them down in the next moon, not same moon (actually confirmed that it happens when done in the same moon as well)
Crash only occurs on interaction success 

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/167268625/889db8ff-89b6-45a0-ae03-1c889db174b5)

**Comment by scribblecrumb** [comment]
Fixed
