### ISSUE TITLE
The Dead Are Aging

### ISSUE THREAD

**Issue by MagiBaxter-Iridescentvow** [scribblecrumb/clangen#37]
**Type**: Code

**Describe the bug**
The dead cats in all of the afterlives are aging. They are not gaining moons dead, but just getting older.

**Grade**:
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. Open or start a clan.
2. Click on Cat List and then Show Dead
3. Click on any dead cat, including the guide and check their age and the moons they have been dead for
4. Skip a moon
5. Check the ages and moons dead again. The moons dead will be the same, but the age will have increased by 1.

**Commit # or Game Version Number**: 9a507fe4c1c1c0aa79ea280e8b76bf105fa1572d

**Additional context**
Exiled, lost, outsider and living cats are all aging as normal

**Comment by scribblecrumb** [comment]
Pretty sure it's fixed
