### ISSUE TITLE
No early retirement for you! [BUG] 

### ISSUE THREAD

**Issue by mycenachlorophos** [scribblecrumb/clangen#38]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
Upon exiling a leader and recruiting them back into the Clan, they lose their leader rank. This is normal, but whats not normal about it is that they also join the Clan as an elder, no matter their age or permanent conditions. 

**Grade**: (only select one)
- Important - The bug has a large affect on the gameplay, but is not urgent

**Reproduce**
1. Exile a leader.
2. In the leaders den screen, recruit the leader back into the Clan.
3. Go to the leaders profile once they've been recruited back into the Clan.
4. Observe the early retirement. 

**Additional context**
This could occur with other ranks as well, but I've only noticed it in the case of leaders.

**Comment by scribblecrumb** [comment]
Hopefully fixed
