### ISSUE TITLE
[BUG] old leader is mentioned in gathering text

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#39]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
despite being exiled, the old leader appears in the gathering moon event

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. choose to interact with another clan
2. exile your leader
3. moon skip

**Commit # or Game Version Number**: latest

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/d85313ee-60dd-435b-939e-7bd78779cb95)
![image](https://github.com/scribblecrumb/clangen/assets/126827015/27ce655d-62c3-4a74-a18d-cf8ce6d36e9c)

**Comment by scribblecrumb** [comment]
Fixed
