### ISSUE TITLE
[BUG] odd behavior when exiling kit

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#40]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
when exiling a kitten and skipping a moon, they age up to 6 moons even if they are 1 moon old, 2 moons old, etc. they are also given a warrior name

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. exile a kitten
2. moon skip

**Commit # or Game Version Number**: latest

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/fe4d91d3-e585-42bb-9c12-4f505cae57ef)

**Comment by scribblecrumb** [comment]
I'm not having luck replicating this, were you able to make this happen more than once?  If so, is there anything else about the cats that might have caused it?

**Comment by scribblecrumb** [comment]
Okay, I think I may have actually stumbled upon the real cause of this!  It should be fixed, but report again if it still occurs
