### ISSUE TITLE
[BUG] unable to invite cat back to camp

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#41]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
even by skipping moons, i am unable to invite an exile cat back to the clan when i previously could

**Grade**: (only select one)
- Important - The bug has a large affect on the gameplay, but is not urgent

**Reproduce**
1. Go to exile a pregnant cat
2. when she gives birth, try to invite her back

**Commit # or Game Version Number**: latest

![image](https://github.com/scribblecrumb/clangen/assets/126827015/776ecd7a-d08f-4bb3-b9f9-0502ff50055e)

**Comment by scribblecrumb** [comment]
This may have been fixed.  Report again if it happens again
