### ISSUE TITLE
[BUG] incorrect capitalization of Clan

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#49]
**Type**: (only select one)
- Typo - misspellings or incorrect grammar - IMPORTANT: this type of "bugs" are collected here:

**Describe the bug**
in this thought, clan shld be Clan

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Go on any border patrol till you meet a loner
2. invite in the loner and fail
3. check their thoughts

**Commit # or Game Version Number**: 0.9.0

![image](https://github.com/scribblecrumb/clangen/assets/126827015/903fedce-1837-4492-b242-d1a91d243fbd)

**Comment by scribblecrumb** [comment]
Just fixed ;)
