### ISSUE TITLE
[BUG] The "None" went bad and has to be replaced

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#55]
**Type**: Code

**Describe the bug**
On timeskip, it says the "None" went bad, referring or trying to refer to some herbs. Currently there are some herbs in the medicine den, and this event is not reflected in the medicine den log.

**Grade**: Unimportant

**Reproduce**
Timeskip until this herb event appears.

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/2323dac3-b58a-4208-9323-0404d042a84e)

**Comment by KiraDragoness** [comment]
Update: the None herb also appears as something my Clan gives to other Clans
![image](https://github.com/scribblecrumb/clangen/assets/121829433/90d7add7-95cb-450f-88a5-80a68c9e91fe)

**Comment by scribblecrumb** [comment]
Fixed

**Comment by scribblecrumb** [comment]
Actually wait, maybe not fixed xD

**Comment by scribblecrumb** [comment]
NOW it's fixed
