### ISSUE TITLE
[BUG] Crash on timeskip

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#56]
**Type**: Code

**Describe the bug**
The game crashed upon timeskip, apparently something to do with leader death.

**Grade**: Game-breaking.

**Reproduce**
Keep timeskipping until this crash occurs.

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/e52e322c-4fbf-451e-b22c-54fba0a78185)

**Comment by scribblecrumb** [comment]
Can't fix without event_id
