### ISSUE TITLE
[BUG] (Second) Crash on timeskip "string indices must be integers"

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#57]
**Type**: Code

**Describe the bug**
The game crashed upon timeskip.

**Grade**: Game-breaking

**Reproduce**
Keep timeskipping until you get this particular crash.

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/c31d45d1-71b7-489d-bf40-55d35820093e)

**Comment by scribblecrumb** [comment]
can't fix without event_id
