### ISSUE TITLE
[BUG] Cats do not die to starvation

### ISSUE THREAD

**Issue by ChickenBatnana** [scribblecrumb/clangen#59]
**Type**: Code 

**Describe the bug**
Cats do not die to starvation. The moon event states that they die, but they stay alive. For leaders, they gradually lose lives, and then they go into the negative rather than dying.

**Grade**: Important

**Reproduce**
The easiest way to reproduce this is to make all the cats elders or medicine cats so that they don't hunt and starve. For a leader, you can have two cats, one of which is a medicine cat or elder, and feed any food that the leader hunts to that cat until the leader is starving

**Commit # or Game Version Number**: 0f229a0510b49e0c0f9f2d5cfcb7672f7122f999

**Screenshots**
Leaders lives in the negative
![image](https://github.com/scribblecrumb/clangen/assets/55719034/821be126-68e2-438a-aad3-f5b51837973a)

The moon event does show up
![image](https://github.com/scribblecrumb/clangen/assets/55719034/250ecb3c-209a-48e9-b594-dfc3f6a9f277)

When elders "die" it also says they "lost a life" as if they had multiple
![image](https://github.com/scribblecrumb/clangen/assets/55719034/4a6c232e-01ea-4226-9ae5-495150d85e8f)

**Comment by scribblecrumb** [comment]
Fixed
