### ISSUE TITLE
[BUG] Cat appears twice under the event's selectable cats in mass death event

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#60]
**Type**: Code

**Describe the bug**
After a mass death event, one of the cats that died in it appeared twice in the buttons below the event.

**Grade**: Unimportant

**Reproduce**
Skip moons until you see a mass death event, see the buttons below to see if any cat is duplicated.

**Event ID**: multi_death_massdeath_rogue1

**Screenshots**
Mr. Mustard is duplicated:
![image](https://github.com/scribblecrumb/clangen/assets/121829433/0568c88a-c7a2-461c-b100-67811daf978f)

**Comment by scribblecrumb** [comment]
Fixed
