### ISSUE TITLE
[BUG] New cat event doesn't appear in miscellaneous tab

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#61]
**Type**: Code

**Describe the bug**
There are some new cat events that don't appear in miscellaneous as they used to, you can only see them if you look in the "all events" tab. I've caught one so far, I'll keep adding event IDs if I find more, since I believe some of them do appear.

**Grade**: Regular

**Reproduce**
Timeskip until a new cat event pops up, check if it appears in the miscellaneous tab or if it's only in all events.

**Event ID**: 
gen_new_cat_anylonerkit1
gen_new_cat_anyotherclancat1
gen_new_cat_anyrogue1

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/105bbabe-47d0-4a96-a9cd-67fadc290364)
![image](https://github.com/scribblecrumb/clangen/assets/121829433/569163f7-eabd-4fa1-9857-e2b828059c17)

**Comment by scribblecrumb** [comment]
Fixed
