### ISSUE TITLE
[BUG] Game crash on timeskip (mangled tail event)

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#62]
**Type**: Code

**Describe the bug**
Game crashed on timeskip.

**Grade**: Game-breaking

**Reproduce**
Timeskip on mountain biome until this crash occurs.

**Event ID**: mtn_injury_mangledtail_anyany1

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/e7effa2c-98da-45fe-9e3b-9ddcacb2d914)

**Comment by scribblecrumb** [comment]
Fixed
