### ISSUE TITLE
[BUG] Cat loses their tail because of a wound but it's not reflected in an event

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#63]
**Type**: Code

**Describe the bug**
A cat had a mangled tail because of a fox and ended up losing their tail, but this event was not reflected upon timeskip, in none of the tabs (not even the "all events" tab). The history text shows the scar text correctly, though.

**Grade**: Regular

**Reproduce**
Have a cat be injured with a mangled tail, then skip until they get the no tail scar and see if the event where this should be notified appears.

**Additional context**
There could be something weird happening here, since I'm using a save file from the main branch. This cat was already injured when I started testing this branch, so I don't know if that could have anything to do with it. 

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/58dcb732-041c-48e2-8ae9-2714c315730b)
![image](https://github.com/scribblecrumb/clangen/assets/121829433/70e3ded5-712d-4a24-bc14-f909ad91dc7d)
![image](https://github.com/scribblecrumb/clangen/assets/121829433/c200e1b1-12e2-4179-adcd-d49a98f59c85)

**Comment by scribblecrumb** [comment]
Keep an eye out for this occurring again and let me know if it does.

**Comment by scribblecrumb** [comment]
Fixed
