### ISSUE TITLE
[BUG] "Relationship block incorrectly formatted"

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#64]
**Type**: Code

**Describe the bug**
There's a print stating a relationship block is incorrectly formatted. The event for which this appears is not present among the moon events.

**Grade**: Non-vital

**Reproduce**
Skip moons and check the prints for the different events.

**Event ID**: gen_misc_any_adultsavingkitapprentice1

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/c5520513-7027-4070-82cd-d925472487db)

**Comment by scribblecrumb** [comment]
Fixed
