### ISSUE TITLE
[BUG] Some events have history formatted incorrectly

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#65]
**Type**: Code

**Describe the bug**
The console is printing a bunch of moon events for whish the history seems to be formatted incorrectly.

**Grade**: Non-vital

**Reproduce**
Timeskip and check the console.

**Event IDs**:
mtn_injury_brokenbone_multiany1
mtn_injury_brokenbone_anyany1
mtn_injury_mangledtail_anyany1
mtn_injury_brokenbone_anyapprentice1

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/e0628284-bdb1-4379-a995-1923f95afcf9)

**Comment by scribblecrumb** [comment]
Fixed
