### ISSUE TITLE
[BUG] "Error in loading faded cat"

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#66]
**Type**: Code

**Describe the bug**
Upon timeskips, there are blocks of "Error in loading faded cat" printing in the console all the time.

**Grade**: Unimportant

**Reproduce**
Not sure? I got a save file transferred to this branch for testing, from the main dev version, where this is not happening.
Maybe try importing a save file of an old enough Clan (with dead cats) to this branch and timeskip to see if this happens too.

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/1cfdd8a2-dd8c-4c4e-9d87-75ba50480f3d)

**Comment by scribblecrumb** [comment]
Fixed
