### ISSUE TITLE
[BUG] Other Clan Names Missing in Moon Event

### ISSUE THREAD

**Issue by thunderingboom** [scribblecrumb/clangen#67]
**Type**: Code

**Describe the bug**
For this save at least when interacting with the other clans via the Leader's Den the name of the clan is replaced with 'o_c' and not the clan I tried interacting with. There are five other clans and this happens with any of them.

**Grade**: Regular

**Reproduce**
Unsure, need to make new save and see if still happens.

**Commit # or Game Version Number**: 
Downloaded today.

**Screenshots**
![2024-06-04](https://github.com/scribblecrumb/clangen/assets/149605071/3bf08d74-6c72-4d6e-b9e2-ab5dd7217f49)

**Comment by scribblecrumb** [comment]
Oh haha I actually just noticed and fixed this lmao
