### ISSUE TITLE
[BUG] Crash on timeskip (leader injury related)

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#69]
**Type**: Code

**Describe the bug**
Game crashes after timeskip, seems to be related to the leader getting injured/dying.

**Grade**: Game-breaking

**Reproduce**
Timeskip in mountain biome until it occurs

**Event ID**: mtn_injury_mangledtail_anyany1

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/eb41334d-a21e-4081-a66d-7ac279f201d8)

**Comment by scribblecrumb** [comment]
Fixed
