### ISSUE TITLE
[BUG] Crash trying to look into a dead cat's history

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#70]
**Type**: Code

**Describe the bug**
I tried to look into the history of a dead cat and the came crashed.

**Grade**: Game-breaking

**Reproduce**
Get any cat to die, try looking into their history.

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/a0cc5509-ae70-4c53-9401-34df9e9f9b8e)

**Comment by scribblecrumb** [comment]
Hopefully fixed
