### ISSUE TITLE
[BUG] Crash on timeskip (not event related)

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#71]
**Type**: Code

**Describe the bug**
The game crashed on timeskip, but there was no event ids this time.

**Grade**: Game-breaking

**Reproduce**
Timeskip until it occurs (?)

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/27c70f2b-02e9-410c-9a2f-c751875aadbf)

**Comment by scribblecrumb** [comment]
Fixed
