### ISSUE TITLE
[BUG] rogue claims to not take a new name, but does

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#72]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 
**Describe the bug**
despite it saying that the loner doesnt take a new name, he does

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. moon skip
2. if a loner joins, check if they actually keep their name or not

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/d32ca44b-aa28-44c1-954e-7b286bdfc01b)

**Comment by scribblecrumb** [comment]
NOTE: Dancing had previously been generated and was known as Dancing while still an Outsider

**Comment by selkirks** [comment]
i had a loner named koi generate a few moons ago. upon joining the clan, his name changed to squirrel. alongside this, he is said to keep his old name but a prefix is added on
![image](https://github.com/scribblecrumb/clangen/assets/126827015/a9bdb84f-e2a7-44a0-8cbf-b15b461a5495)

![image](https://github.com/scribblecrumb/clangen/assets/126827015/b3af832c-8767-4f81-8a56-6f312cc2efb9)

![image](https://github.com/scribblecrumb/clangen/assets/126827015/8a28cfad-aa4e-41bf-9afb-3c4519080f3f)

![image](https://github.com/scribblecrumb/clangen/assets/126827015/4f159fce-535e-43f3-b63a-3d501454611d)

**Comment by scribblecrumb** [comment]
I think I've got it fixed!
