### ISSUE TITLE
[BUG] "this should not appear" in history

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#73]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
"this should not appear" appears in the history of a cat who was murdered by being pushed under a monster

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. moon skip
2. when a cat kills another by pushing em under a monster, check the victim's history

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/8b5a7d76-4159-4ec2-95a0-358073182fd9)
![image](https://github.com/scribblecrumb/clangen/assets/126827015/adc3c192-a550-4c9b-b034-60366bb6c2b2)

**Comment by scribblecrumb** [comment]
Fixed
