### ISSUE TITLE
[BUG] repeated "the clan has encountered this loner"

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#74]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
"the clan has encountered LONER" should only be written once per moon event. it appears twice in one

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. moonskip
2. pray that you find a new loner and have another event with them in the same moon

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/3709db96-ab94-459a-91eb-517b71c5358b)

**Comment by scribblecrumb** [comment]
Fixed
