### ISSUE TITLE
[BUG] 0 of a herb appears

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#75]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
i forgot to take a screenshot but i swear on my life this happened. when hovering over the med cat screen and looking at my herb count, i noticed i had '0 lungwort'. this is a bug because when a herb depletes to 0, it is removed from the den. lungwort was not, though

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. im gonna try and guess how it happened hered
2. moonskip and see if you get any events for another clan requesting herbs
3. im guessing if your clan uses the herb and gives it away in the same moon, this bug happens

**Commit # or Game Version Number**: 0.9.0

**Screenshots**

**Comment by selkirks** [comment]
RIGHT after posting this i got it to occur again. looks like an issue with another clan requesting herbs (lungwort is used to cure yellowcough)
![image](https://github.com/scribblecrumb/clangen/assets/126827015/86463a0a-6f4b-4cde-8852-b0ed7a0254fb)
![image](https://github.com/scribblecrumb/clangen/assets/126827015/fab6f8aa-5656-4c47-9e66-00748e2fdc6c)

**Comment by scribblecrumb** [comment]
Fixed
