### ISSUE TITLE
[BUG] relationship block incorrectly formatted

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#76]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
gen_misc_any_medicinecatscandolous2 has a relationship block thats incorrectly formatted. cats_from should be first in the block 

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. moonskip check to see if you get gen_misc_any_medicinecatscandolous2

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: 0.9.0

**Additional context**

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/f8630fb9-3a82-46a5-a403-86ed72c3d3b8)
![image](https://github.com/scribblecrumb/clangen/assets/126827015/2db5c30d-ed66-4cdd-9dfc-7a5a805d9ffe)

**Comment by scribblecrumb** [comment]
Fixed
