### ISSUE TITLE
[BUG] 0 kits are born from a pregnancy

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#77]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
i dont even know what happened here dawg. i was moonskipping, saved and quit (i think the events may have gotten cleared upon leaving? ill try and reproduce. it was weird). went back in and skipped a moon and a pregnant cat gave birth to Zero

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. moonskip
2. periodically save and quit when a pregnant cat is announced
3. see if you can reproduce

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/7b599a3b-379d-4fd9-b3cb-20c23390bc63)

**Comment by selkirks** [comment]
once again i report a bug and then immediately recreate it after. what is my luck.
this occurs when the game is unable to go to the next moon. periodically, when clicking 'skip a moon', the loading animation plays but it never loads the next moon. when you click the 'x' to leave the game, it prompts you to save. select save. upon reopening the game, all moon events are cleared except for 1. i am assuming that the events 'rollback' somehow and that if a cat gets a pregnant condition, this occurs, and then the game acts as if the event didn't happen and never sets a kit amount

https://github.com/scribblecrumb/clangen/assets/126827015/d95791ff-3247-4afd-bc3f-e4732be0f315

**Comment by scribblecrumb** [comment]
fixed
