### ISSUE TITLE
[BUG] kittypet takes on a new name but its the same name

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#78]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
despite marcy being said to take on a new name, she stays with the name marcy

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. moonskip till a loner joins

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/9e6e4f20-a89f-4738-bf34-62f3bf995208)

**Comment by scribblecrumb** [comment]
Fixed
