### ISSUE TITLE
[BUG] missing word in moon event

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#79]
**Type**: (only select one)
- Typo - misspellings or incorrect grammar - IMPORTANT: this type of "bugs" are collected here:

**Describe the bug**
missing word between "his" and the comma

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. have an elder get ticks
2. moon skip till you see this event

**Patrol ID + Outcome Print (if applicable)**:

**Commit # or Game Version Number**: 0.9.0

**Additional context**

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/d400fa42-6e23-4c0b-a3ad-5536f7e15e53)

**Comment by scribblecrumb** [comment]
Fixed
