### ISSUE TITLE
[BUG] crash upon moon skip

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#80]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 
**Describe the bug**
when moon skipping in a classic mode clan, the game can crash

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. make a new classic clan
2. moonskipp till you crash

**Commit # or Game Version Number**: 0.9.0

**Additional context**

**Screenshots**
[stderr_20240605_150118.log](https://github.com/user-attachments/files/15595405/stderr_20240605_150118.log)

**Comment by scribblecrumb** [comment]
Fixed
