### ISSUE TITLE
[BUG] mountain clan cat was dragged into ocean

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#81]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
despite being in the mountains, a moon event for ocean biomes occurs

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. make a mountain clan
2. moon skip

**Event ID + Outcome Print (if applicable)**: CHOSEN: gen_injury_waterintheirlungs_anymultiage1

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/58a00019-aeda-4d8b-b81c-79c162e017b6)
![image](https://github.com/scribblecrumb/clangen/assets/126827015/6d15a389-5fc5-4e58-ab20-1183c9326bcf)

**Comment by scribblecrumb** [comment]
Fixed
