### ISSUE TITLE
[BUG] sentence fragment in history

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#82]
**Type**: (only select one)
- Typo - misspellings or incorrect grammar - IMPORTANT: this type of "bugs" are collected here:

**Describe the bug**
when checking the history of a cat who was scarred from fighting rats who tried to steal the freshkill pile, it is an incomplete sentence

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. moonskipp
2. when a cat defends the fresh kill pile from rats and is scarred, check their history

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/b1144081-168d-435c-b77c-7e44dac1c1a2)

**Comment by scribblecrumb** [comment]
Fixed
