### ISSUE TITLE
[BUG] murder reveal does not show in history

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#83]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
despite a murderer being revealed, it does not show in the history of the murder

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. moonskip till a cat kills another
2. moonskip till that murder is revealed
3. check history of murderer

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/cd3bf1aa-165b-4212-8138-353dab8ca4a6)
![image](https://github.com/scribblecrumb/clangen/assets/126827015/6187ce59-38e5-4729-a137-88f25f9e4e85)

**Comment by scribblecrumb** [comment]
Fixed
