### ISSUE TITLE
[BUG] checking history of cat crashes game

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#84]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
when clicking the history file of a dead, exiled cat, it crashes the game

**Grade**: (only select one)
- Important - The bug has a large affect on the gameplay, but is not urgent

**Reproduce**
1. exile a pregnant cat
2. when one of her outsider kits dies, check their history

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
[stderr_20240605_210023.log](https://github.com/user-attachments/files/15598231/stderr_20240605_210023.log)

**Comment by scribblecrumb** [comment]
Hmm interesting, I can't seem to replicate this one

**Comment by selkirks** [comment]
> Hmm interesting, I can't seem to replicate this one

would you like me to drag and drop my saves folder for that clan?

**Comment by selkirks** [comment]
im pretty sure this crash has no rime or reason- it randomly happens when a cat dies. its so odd because sometimes it crashes and sometimes it doesnt. but whenever i save my game, it doesnt crash so i cant send my saves file

**Comment by selkirks** [comment]
[Cloudclan.json](https://github.com/user-attachments/files/15687224/Cloudclan.json)
[clan_cats.json](https://github.com/user-attachments/files/15687225/clan_cats.json)

**Comment by scribblecrumb** [comment]
Fixed
