### ISSUE TITLE
[BUG] Cat rejoining the Clan becomes a warrior before they rejoin

### ISSUE THREAD

**Issue by ChickenBatnana** [scribblecrumb/clangen#85]
**Type**: Code

**Describe the bug**
When rejoining the Clan, the message that the lost cat becomes a warrior is displayed before the message that they're rejoining

**Grade**: Unimportant

**Reproduce**
Lose an apprentice, skip moons until they are of warrior age, invite them back through the leader den

**Commit # or Game Version Number**: d68c339e2e13e70a8be692e256b0bd82e1c0b378

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/55719034/37bcd454-76e1-47ca-b78e-3d70b82d948d)

**Comment by scribblecrumb** [comment]
Since this is through the Leader Den, it's actually a Dev bug!  Go ahead and report it on the main ClanGen github, please
