### ISSUE TITLE
[BUG] apprentice-aged warrior

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#86]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
an apprentice-aged warrior joins the clan

**Grade**: (only select one)
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. exile a pregnant cat
2. moon skip and there is a possibility an apprentice-aged kit of theirs joins as a warrior

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/8bf45fff-c60a-4935-89be-8537a6bc3c3e)
![image](https://github.com/scribblecrumb/clangen/assets/126827015/2163d711-cf7b-4660-a49c-6fbc95203ea5)

**Comment by scribblecrumb** [comment]
Fixed
