### ISSUE TITLE
[BUG] when a kit dies and you click their history, the game crashes

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#87]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
i had a kit named houndkit die by being found dead near another clan's border. upon clicking his history, the game crashed

**Grade**: (only select one)
- Important - The bug has a large affect on the gameplay, but is not urgent

**Reproduce**
1. have a kit in your clan
2. hope they are killed near an enemy clan's border
3. check their history

**Commit # or Game Version Number**: 0.9.0

**Screenshots**
[stderr_20240606_181127.log](https://github.com/user-attachments/files/15687005/stderr_20240606_181127.log)

**Comment by scribblecrumb** [comment]
Fixed
