### ISSUE TITLE
[BUG] kit is described as a healer

### ISSUE THREAD

**Issue by selkirks** [scribblecrumb/clangen#88]
**Type**: (only select one)
- Typo - misspellings or incorrect grammar

**Describe the bug**
an outsider, five moon old kit is described as a healer when they are too young to be knowledgable about the subject

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. exile a pregnant cat
2. see if one of ur cats meets one of the exiled cat's kittens

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/126827015/cc74a89e-6493-4b83-a245-43b31e4cd4d0)

**Comment by scribblecrumb** [comment]
Fixed
