### ISSUE TITLE
[BUG] Crash upon timeskip

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#90]
**Type**: Code

**Describe the bug**
The game crashed after trying to timeskip, seemingly related to death history and o_c_n

**Grade**: Game-breaking

**Reproduce**
Timeskip until you run into this crash.

**Event ID**: 
gen_death_age_any4
Happened again with this event: gen_death_murder_any1

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/5ba60851-3b8c-49f2-b1f8-7ccf867d601a)

**Comment by scribblecrumb** [comment]
Fixed
