### ISSUE TITLE
[BUG] Death event doesn't kill cat

### ISSUE THREAD

**Issue by KiraDragoness** [scribblecrumb/clangen#91]
**Type**: Code

**Describe the bug**
A death event related to the fresh-kill pile doesn't actually kill the cat even though it's stated it should have.

**Grade**: Important

**Reproduce**
1. Have a large fresh-kill pile
2. Skip moons until this event takes place, check if the cat is actually dead.

**Event ID**: gen_death_freshkill_anyfox1

**Screenshots**
![image](https://github.com/scribblecrumb/clangen/assets/121829433/f46d3fec-fd2c-4175-8548-54b4e26c5207)
![image](https://github.com/scribblecrumb/clangen/assets/121829433/493ab0de-7448-4a04-802d-dfa79e6aaf9a)

**Comment by scribblecrumb** [comment]
Fixed
